version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: bamboo
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.0
    - 3.7.2
    - 3.7.3
  - dependency-name: hackney
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: ex_machina
    versions:
    - 2.5.0
    - 2.6.0
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: tesla
    versions:
    - 1.4.0
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
  - dependency-name: plug
    versions:
    - 1.11.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
  - dependency-name: excoveralls
    versions:
    - 0.13.4
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.3
  - dependency-name: algoliasearch
    versions:
    - 4.8.4
    - 4.8.5
    - 4.8.6
    - 4.9.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: instantsearch.js
    versions:
    - 4.13.1
    - 4.13.2
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: mapbox-gl
    versions:
    - 2.0.1
    - 2.1.0
    - 2.1.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.4.1
  - dependency-name: expose-loader
    versions:
    - 1.0.3
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.0
    - 3.6.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
