version: '3'

services:
  # Phoenix app
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        HOST_USER_UID: ${HOST_USER_UID}
        HOST_GROUP_GID: ${HOST_GROUP_GID}
    container_name: openpace-app
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - db

  # Postgres
  db:
    image: postgres:latest
    container_name: openpace-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

volumes:
  pgdata:
