import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :squeeze, SqueezeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# In application.ex, we allow fit decoder workers but not in production
config :squeeze, :allow_strava_upload, false

# Using rustler and a precompiled NIF in the build
config :squeeze, Squeeze.RustFit,
  crate: :rust_fit,
  skip_compilation?: true,
  load_from: {:squeeze, "priv/native/librust_fit"}
