[package]
name = "rust_fit"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rust_fit"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
fitparser = "0.7.0"
rustler = "0.34.0"

